version: 2.1
executors:
  default:
    docker:
      - image: cimg/node:22.7.0

orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-s3: circleci/aws-s3@4.0

jobs:
  build:
    executor: default
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Build Next.js app
          command: npm run build

      - aws-cli/setup:
          name: Configure AWS CLI
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          aws-region: us-east-2

      - aws-s3/sync:
          name: Upload build to S3
          from: ./out
          to: s3://menmoneymeaning

      # - run:
      #     name: Upload build to S3
      #     command: |
      #       aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      #       aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      #       aws s3 sync ./out s3://menmoneymeaning
      - run:
          name: Invalidate CloudFront distribution
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws cloudfront create-invalidation --distribution-id E1GGPRX84AEGIR --paths "/*"

workflows:
  build-workflow:
    jobs:
      - build:
          context:
            - AWS